spring:
  datasource:
    url: jdbc:mysql://localhost:3306/binaaz
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password
  resources:
    static:
      location: classpath:/static/
  mail:
    host: sandbox.smtp.mailtrap.io
    username: ef10a562d958bd
    password: 0d949e0c2eb0c6
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

server:
  port: 8085