logging:
  level:
    root: info

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lemlistapp
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

    database: mysql


  mail:
    host: smtp.gmail.com
    username: "nubarqasimova05@gmail.com"
    password: "Bar130805"
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true





url:
  ignore:
    swagger: /v2/api-docs, /webjars/*, /swagger-resources/, /actuator/health, /swagger-ui/index.html, /swagger-ui.html, /app//.{js,html}

springdoc:
  swagger-ui:
    path: /swagger
